---
 - hosts: all
   become: true
   pre_tasks:
   - name: install updates (CentOS)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "CentOS"

   - name: install updates (Ubuntu)
     tags: always
     apt:
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

 - hosts: web_server
   become: true
   tasks:
   - name: install apache and php (Ubuntu)
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"

   - name: install apache and php (CentOS)
     tags: apache,httpd,centos
     dnf:
       name: 
         - httpd
         - php
       state: latest
     when: ansible_distribution == "CentOS"

   - name: start service httpd
     tags: service
     ansible.builtin.service:
       name: httpd
       state: started
       enabled: yes
     when: ansible_distribution == "CentOS"

   - name: cahge e-mail adress for admin
     tags: apache,centos,httpd
     lineinfile:
       path: /etc/httpd/conf/httpd.conf
       regexp: '^ServerAdmin'
       line: ServerAdmin somebody@somewhere.net
     when: ansible_distribution == "CentOS"
     register: httpd

   - name: restart httpd (CentOS)
     tags: apache,centos,httpd
     ansible.builtin.service:
       name: httpd
       state: restarted
     when: httpd.changed

   - name: copy default html for site
     tags: apache,apache2,httpd
     copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

 - hosts: workstation
   become: true
   tasks:
   - name: install unzip
     package:
       name: unzip

   - name: install terraform
     unarchive:
       src: https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root

 - hosts: db_server
   become: true
   tasks:
   - name: install mariadb package (CentOS)
     tags: db,mariadb,centos
     dnf:
       name: mariadb
       state: latest
     when: ansible_distribution == "CentOS"

   - name: install mariadb package (Ubuntu)
     tags: db,mariadb,ubuntu
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"

 - hosts: files_server
   become: true
   tasks:
   - name: install samba package
     tags: samba
     package: 
       name: samba
       state: latest
